### ISSUE TITLE
getting error - php version not match, please help

### ISSUE THREAD

**Issue by sushantj651** [AnyDownloader/InstagramDownloader#2]
getting error - php version not match, please help
![error1](https://user-images.githubusercontent.com/66820819/129837935-a7d61ef0-9a7a-4c33-9a7c-64d6dc4bbc13.png)

**Comment by intracomof** [comment]
Hi, 

it should work now, try one more time

**Comment by sushantj651** [comment]
getting this in terminal
"Using version dev-master for any-downloader/instagram-downloader
Root package 'any-downloader/instagram-downloader' cannot require itself in its composer.json"

**Comment by intracomof** [comment]
Run `composer clear-cache` 
and then `composer require any-downloader/instagram-downloader`

**Comment by sushantj651** [comment]
lib installed successfully but when I use, it's give me error
![error2](https://user-images.githubusercontent.com/66820819/129846818-8cff2e41-1458-4e36-8825-d734f5939333.png)

**Comment by intracomof** [comment]
Make sure that path to `vendor` folder is correct.

Btw, this Instagram post https://www.instagram.com/p/CPymPNfBvnM/ is not available anymore so put link to another one

**Comment by sushantj651** [comment]
I give correct `vendor` path but its says (Undefined type 'AnyDownloader\DownloadManager\Model\URL') and same as for InstagramHandler (Undefined type 'AnyDownloader\InstagramDownloader\InstagramHandler')

**Comment by intracomof** [comment]
Seems like composer package wasn't installed, check existence of `./vendor/any-downloader/download-manager` and `./vendor/any-downloader/instagram-downloader` folders.

**Comment by sushantj651** [comment]
Both `download-manager` and `instagram-downloader` folder exist in `./vendor/any-downloader` . 
The error is now gone for `URL` and `InstagramHandler()` , but cant find `use Goutte\Client;` 
Now error only shown in `new Client()`

**Comment by intracomof** [comment]
Your system uses different PHP versions for CLI and for web, fix it and then reinstall packages from scratch:
`composer clear-cache`
`composer require any-downloader/instagram-downloader`

**Comment by sushantj651** [comment]
Ok, I'll try.

**Comment by sushantj651** [comment]
I also use file_get_content($post_url) method to get the html code. It works fine in local server on my pc but when I upload in server this method gives me error

file_get_content($post_url): failed to open stream http request failed http/1.1 429

**Comment by sushantj651** [comment]
I fix the issue now its working fine in Local server but when I upload on live server then in Array it's not return anything. Is there something I have to do in live server? Like in SSH something?

**Comment by intracomof** [comment]
I'd suggest you to turn on display_errors and debug this script on your server. There could be many different reasons for such issue

**Comment by sushantj651** [comment]
There is error
`Uncaught AnyDownloader\DownloadManager\Exception\NothingToExtractException` in
`vendor/any-downloader/instagram-downloader/src/InstagramHandler.php:51`

**Comment by intracomof** [comment]
Handler can not find json within html page.
```php
if (stripos($crawler->html(), 'window._sharedData = ') === false) {
```

You should check Instagram response in php script

**Comment by Babbar1322** [comment]
hello sir,
problem is actually in short code at this line........
$media = $sharedData->entry_data->PostPage[0]->graphql->shortcode_media;


<br />
<b>Notice</b>: Undefined property: stdClass::$PostPage in
<b>/home/webcys2/public_html/instaVideoApp/vendor/any-downloader/instagram-downloader/src/InstagramHandler.php</b> on
line <b>59</b><br />
<br />
<b>Notice</b>: Trying to get property 'graphql' of non-object in
<b>/home/webcys2/public_html/instaVideoApp/vendor/any-downloader/instagram-downloader/src/InstagramHandler.php</b> on
line <b>59</b><br />
<br />
<b>Notice</b>: Trying to get property 'shortcode_media' of non-object in
<b>/home/webcys2/public_html/instaVideoApp/vendor/any-downloader/instagram-downloader/src/InstagramHandler.php</b> on
line <b>59</b><br />

**Comment by Babbar1322** [comment]
$sharedData->entry_data->PostPage[0]

entry_data return some data without included  postpage object.. something wrong in this object .. this is main problem in my case.

**Comment by intracomof** [comment]
> $sharedData->entry_data->PostPage[0]
> 
> entry_data return some data without included postpage object.. something wrong in this object .. this is main problem in my case.

Instagram returns to your live server a broken response with no PostPage data. You should try to use InstagramHandler with proxy (look at the bottom of [Readme](https://github.com/AnyDownloader/InstagramDownloader/))

**Comment by Babbar1322** [comment]
i'm used proxy like ....
        $instagramPostUrl = URL::fromString($mystring);
        $downloadManager = new DownloadManager();
        
        $client = new Client(HttpClient::create(['proxy' => 'https://webcyst.com/instaVideoApp/'])); 
        $instagramHandler = new InstagramHandler($client);
        
        $downloadManager->addHandler(new InstagramHandler(new Client()));
        $result = $downloadManager->fetchResource($instagramPostUrl);
        $cc = array_values($result->toArray());



but i got errro like ......

br />
<b>Fatal error</b>: Uncaught Error: Class 'HttpClient' not found in /home/webcys2/public_html/instaVideoApp/test.php:47
Stack trace:
#0 {main}
thrown in <b>/home/webcys2/public_html/instaVideoApp/test.php</b> on line <b>47</b><br />

**Comment by Babbar1322** [comment]
where is the file path of HttpClient function ??

**Comment by intracomof** [comment]
put `use Symfony\Component\HttpClient\HttpClient;` at the top of the file

**Comment by Babbar1322** [comment]
i already put this in my coding file

use AnyDownloader\DownloadManager\DownloadManager;
use AnyDownloader\DownloadManager\Model\URL;
use AnyDownloader\InstagramDownloader\InstagramHandler;
use Symfony\Component\HttpClient\HttpClient;
use Goutte\Client;

but nothing is new..  same error again 

<br />
<b>Notice</b>: Undefined property: stdClass::$PostPage in
<b>/home/webcys2/public_html/instaVideoApp/vendor/any-downloader/instagram-downloader/src/InstagramHandler.php</b> on
line <b>58</b><br />
<br />
<b>Notice</b>: Trying to get property 'graphql' of non-object in
<b>/home/webcys2/public_html/instaVideoApp/vendor/any-downloader/instagram-downloader/src/InstagramHandler.php</b> on
line <b>58</b><br />
<br />
<b>Notice</b>: Trying to get property 'shortcode_media' of non-object in
<b>/home/webcys2/public_html/instaVideoApp/vendor/any-downloader/instagram-downloader/src/InstagramHandler.php</b> on
line <b>58</b><br />
<br />
<b>Fatal error</b>: Uncaught AnyDownloader\DownloadManager\Exception\NothingToExtractException in
/home/webcys2/public_html/instaVideoApp/vendor/any-downloader/instagram-downloader/src/InstagramHandler.php:60
Stack trace:
#0 /home/webcys2/public_html/instaVideoApp/vendor/any-downloader/download-manager/src/DownloadManager.php(27):
AnyDownloader\InstagramDownloader\InstagramHandler-&gt;fetchResource(Object(AnyDownloader\DownloadManager\Model\URL))
#1 /home/webcys2/public_html/instaVideoApp/test.php(55):
AnyDownloader\DownloadManager\DownloadManager-&gt;fetchResource(Object(AnyDownloader\DownloadManager\Model\URL))
#2 {main}
thrown in
<b>/home/webcys2/public_html/instaVideoApp/vendor/any-downloader/instagram-downloader/src/InstagramHandler.php</b> on
line <b>60</b><br />

**Comment by intracomof** [comment]
Probably, bad proxy 🤔

**Comment by Babbar1322** [comment]
please suggest me how can i set proxy url ... ( i set my project server path in place of  proxy url ).. instead of path what should i do for correct proxy .

**Comment by intracomof** [comment]
Please, run `composer update` to refetch InstagramDownloader library

**Comment by intracomof** [comment]
Also I have to mention that proxy will not work with no cookies sent. Grab cookies from your browser and add them as Client request header like this   
```php
$client = new Client(HttpClient::create([
    'proxy' => '<proxy value>',
    'headers' => [
        'cookie' => '<cookie value>'
    ]
]));
```

**Comment by Babbar1322** [comment]
sorry but i face again same error .. now error in your new code that you replace in Handler file 

<br />
<b>Notice</b>: Undefined property: stdClass::$PostPage in
<b>/home/webcys2/public_html/instaVideoApp/newproj/src/InstagramHandler.php</b> on line <b>161</b><br />
<br />
<b>Notice</b>: Trying to get property 'graphql' of non-object in
<b>/home/webcys2/public_html/instaVideoApp/newproj/src/InstagramHandler.php</b> on line <b>161</b><br />
<br />
<b>Notice</b>: Trying to get property 'shortcode_media' of non-object in
<b>/home/webcys2/public_html/instaVideoApp/newproj/src/InstagramHandler.php</b> on line <b>161</b><br />
<br />
<b>Notice</b>: Undefined offset: 1 in <b>/home/webcys2/public_html/instaVideoApp/newproj/src/InstagramHandler.php</b> on
line <b>143</b><br />
<br />
<b>Fatal error</b>: Uncaught AnyDownloader\DownloadManager\Exception\NothingToExtractException in
/home/webcys2/public_html/instaVideoApp/newproj/src/InstagramHandler.php:59
Stack trace:
#0 /home/webcys2/public_html/instaVideoApp/newproj/vendor/any-downloader/download-manager/src/DownloadManager.php(27):
AnyDownloader\InstagramDownloader\InstagramHandler-&gt;fetchResource(Object(AnyDownloader\DownloadManager\Model\URL))
#1 /home/webcys2/public_html/instaVideoApp/newproj/test.php(57):
AnyDownloader\DownloadManager\DownloadManager-&gt;fetchResource(Object(AnyDownloader\DownloadManager\Model\URL))
#2 {main}
thrown in <b>/home/webcys2/public_html/instaVideoApp/newproj/src/InstagramHandler.php</b> on line <b>59</b><br />

**Comment by intracomof** [comment]
if you found a solution, you can make pull request
